<?php

namespace Database\Seeders;

use App\Models\PickingCostScale;
use Illuminate\Database\Seeder;

class PickingCostScaleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $scales = [
            [
                'quantity_from' => 1,
                'quantity_to' => 49,
                'cost_without_assembly' => 10,
                'cost_with_assembly' => 10,
                'palletizing_without_pallet' => 10,
                'palletizing_with_pallet' => 10,
                'cost_with_labeling' => 10,
                'cost_without_labeling' => 10,
                'dome_sticking_unit' => 10,
                'additional_assembly' => 10,
                'quality_control' => 10,
                'shavings_50g_unit' => 10,
                'shavings_100g_unit' => 10,
                'shavings_200g_unit' => 10,
                'bag_10x15_unit' => 10,
                'bag_20x30_unit' => 10,
                'bag_35x45_unit' => 10,
                'bubble_wrap_5x10_unit' => 10,
                'bubble_wrap_10x15_unit' => 10,
                'bubble_wrap_20x30_unit' => 10,
                'production_time' => '24 hs',
            ],
            [
                'quantity_from' => 50,
                'quantity_to' => 84,
                'cost_without_assembly' => 20,
                'cost_with_assembly' => 20,
                'palletizing_without_pallet' => 20,
                'palletizing_with_pallet' => 20,
                'cost_with_labeling' => 20,
                'cost_without_labeling' => 20,
                'dome_sticking_unit' => 20,
                'additional_assembly' => 20,
                'quality_control' => 20,
                'shavings_50g_unit' => 20,
                'shavings_100g_unit' => 20,
                'shavings_200g_unit' => 20,
                'bag_10x15_unit' => 20,
                'bag_20x30_unit' => 20,
                'bag_35x45_unit' => 20,
                'bubble_wrap_5x10_unit' => 20,
                'bubble_wrap_10x15_unit' => 20,
                'bubble_wrap_20x30_unit' => 20,
                'production_time' => '24 hs',
            ],
            [
                'quantity_from' => 85,
                'quantity_to' => 99,
                'cost_without_assembly' => 30,
                'cost_with_assembly' => 30,
                'palletizing_without_pallet' => 30,
                'palletizing_with_pallet' => 30,
                'cost_with_labeling' => 30,
                'cost_without_labeling' => 30,
                'dome_sticking_unit' => 30,
                'additional_assembly' => 30,
                'quality_control' => 30,
                'shavings_50g_unit' => 30,
                'shavings_100g_unit' => 30,
                'shavings_200g_unit' => 30,
                'bag_10x15_unit' => 30,
                'bag_20x30_unit' => 30,
                'bag_35x45_unit' => 30,
                'bubble_wrap_5x10_unit' => 30,
                'bubble_wrap_10x15_unit' => 30,
                'bubble_wrap_20x30_unit' => 30,
                'production_time' => '48 hs',
            ],
            [
                'quantity_from' => 100,
                'quantity_to' => 149,
                'cost_without_assembly' => 40,
                'cost_with_assembly' => 40,
                'palletizing_without_pallet' => 40,
                'palletizing_with_pallet' => 40,
                'cost_with_labeling' => 40,
                'cost_without_labeling' => 40,
                'dome_sticking_unit' => 40,
                'additional_assembly' => 40,
                'quality_control' => 40,
                'shavings_50g_unit' => 40,
                'shavings_100g_unit' => 40,
                'shavings_200g_unit' => 40,
                'bag_10x15_unit' => 40,
                'bag_20x30_unit' => 40,
                'bag_35x45_unit' => 40,
                'bubble_wrap_5x10_unit' => 40,
                'bubble_wrap_10x15_unit' => 40,
                'bubble_wrap_20x30_unit' => 40,
                'production_time' => '48 hs',
            ],
            [
                'quantity_from' => 150,
                'quantity_to' => 249,
                'cost_without_assembly' => 50,
                'cost_with_assembly' => 50,
                'palletizing_without_pallet' => 50,
                'palletizing_with_pallet' => 50,
                'cost_with_labeling' => 50,
                'cost_without_labeling' => 50,
                'dome_sticking_unit' => 50,
                'additional_assembly' => 50,
                'quality_control' => 50,
                'shavings_50g_unit' => 50,
                'shavings_100g_unit' => 50,
                'shavings_200g_unit' => 50,
                'bag_10x15_unit' => 50,
                'bag_20x30_unit' => 50,
                'bag_35x45_unit' => 50,
                'bubble_wrap_5x10_unit' => 50,
                'bubble_wrap_10x15_unit' => 50,
                'bubble_wrap_20x30_unit' => 50,
                'production_time' => '72 hs',
            ],
            [
                'quantity_from' => 250,
                'quantity_to' => 299,
                'cost_without_assembly' => 60,
                'cost_with_assembly' => 60,
                'palletizing_without_pallet' => 60,
                'palletizing_with_pallet' => 60,
                'cost_with_labeling' => 60,
                'cost_without_labeling' => 60,
                'dome_sticking_unit' => 60,
                'additional_assembly' => 60,
                'quality_control' => 60,
                'shavings_50g_unit' => 60,
                'shavings_100g_unit' => 60,
                'shavings_200g_unit' => 60,
                'bag_10x15_unit' => 60,
                'bag_20x30_unit' => 60,
                'bag_35x45_unit' => 60,
                'bubble_wrap_5x10_unit' => 60,
                'bubble_wrap_10x15_unit' => 60,
                'bubble_wrap_20x30_unit' => 60,
                'production_time' => '72 hs',
            ],
            [
                'quantity_from' => 300,
                'quantity_to' => 399,
                'cost_without_assembly' => 70,
                'cost_with_assembly' => 70,
                'palletizing_without_pallet' => 70,
                'palletizing_with_pallet' => 70,
                'cost_with_labeling' => 70,
                'cost_without_labeling' => 70,
                'dome_sticking_unit' => 70,
                'additional_assembly' => 70,
                'quality_control' => 70,
                'shavings_50g_unit' => 70,
                'shavings_100g_unit' => 70,
                'shavings_200g_unit' => 70,
                'bag_10x15_unit' => 70,
                'bag_20x30_unit' => 70,
                'bag_35x45_unit' => 70,
                'bubble_wrap_5x10_unit' => 70,
                'bubble_wrap_10x15_unit' => 70,
                'bubble_wrap_20x30_unit' => 70,
                'production_time' => '3 dias',
            ],
            [
                'quantity_from' => 400,
                'quantity_to' => 499,
                'cost_without_assembly' => 80,
                'cost_with_assembly' => 80,
                'palletizing_without_pallet' => 80,
                'palletizing_with_pallet' => 80,
                'cost_with_labeling' => 80,
                'cost_without_labeling' => 80,
                'dome_sticking_unit' => 80,
                'additional_assembly' => 80,
                'quality_control' => 80,
                'shavings_50g_unit' => 80,
                'shavings_100g_unit' => 80,
                'shavings_200g_unit' => 80,
                'bag_10x15_unit' => 80,
                'bag_20x30_unit' => 80,
                'bag_35x45_unit' => 80,
                'bubble_wrap_5x10_unit' => 80,
                'bubble_wrap_10x15_unit' => 80,
                'bubble_wrap_20x30_unit' => 80,
                'production_time' => '4 dias',
            ],
            [
                'quantity_from' => 500,
                'quantity_to' => 799,
                'cost_without_assembly' => 90,
                'cost_with_assembly' => 90,
                'palletizing_without_pallet' => 90,
                'palletizing_with_pallet' => 90,
                'cost_with_labeling' => 90,
                'cost_without_labeling' => 90,
                'dome_sticking_unit' => 90,
                'additional_assembly' => 90,
                'quality_control' => 90,
                'shavings_50g_unit' => 90,
                'shavings_100g_unit' => 90,
                'shavings_200g_unit' => 90,
                'bag_10x15_unit' => 90,
                'bag_20x30_unit' => 90,
                'bag_35x45_unit' => 90,
                'bubble_wrap_5x10_unit' => 90,
                'bubble_wrap_10x15_unit' => 90,
                'bubble_wrap_20x30_unit' => 90,
                'production_time' => '4 dias',
            ],
            [
                'quantity_from' => 800,
                'quantity_to' => 999,
                'cost_without_assembly' => 100,
                'cost_with_assembly' => 100,
                'palletizing_without_pallet' => 100,
                'palletizing_with_pallet' => 100,
                'cost_with_labeling' => 100,
                'cost_without_labeling' => 100,
                'dome_sticking_unit' => 100,
                'additional_assembly' => 100,
                'quality_control' => 100,
                'shavings_50g_unit' => 100,
                'shavings_100g_unit' => 100,
                'shavings_200g_unit' => 100,
                'bag_10x15_unit' => 100,
                'bag_20x30_unit' => 100,
                'bag_35x45_unit' => 100,
                'bubble_wrap_5x10_unit' => 100,
                'bubble_wrap_10x15_unit' => 100,
                'bubble_wrap_20x30_unit' => 100,
                'production_time' => '4 dias',
            ],
            [
                'quantity_from' => 1000,
                'quantity_to' => 1999,
                'cost_without_assembly' => 110,
                'cost_with_assembly' => 110,
                'palletizing_without_pallet' => 110,
                'palletizing_with_pallet' => 110,
                'cost_with_labeling' => 110,
                'cost_without_labeling' => 110,
                'dome_sticking_unit' => 110,
                'additional_assembly' => 110,
                'quality_control' => 110,
                'shavings_50g_unit' => 110,
                'shavings_100g_unit' => 110,
                'shavings_200g_unit' => 110,
                'bag_10x15_unit' => 110,
                'bag_20x30_unit' => 110,
                'bag_35x45_unit' => 110,
                'bubble_wrap_5x10_unit' => 110,
                'bubble_wrap_10x15_unit' => 110,
                'bubble_wrap_20x30_unit' => 110,
                'production_time' => '5 dias',
            ],
            [
                'quantity_from' => 2000,
                'quantity_to' => 4999,
                'cost_without_assembly' => 120,
                'cost_with_assembly' => 120,
                'palletizing_without_pallet' => 120,
                'palletizing_with_pallet' => 120,
                'cost_with_labeling' => 120,
                'cost_without_labeling' => 120,
                'dome_sticking_unit' => 120,
                'additional_assembly' => 120,
                'quality_control' => 120,
                'shavings_50g_unit' => 120,
                'shavings_100g_unit' => 120,
                'shavings_200g_unit' => 120,
                'bag_10x15_unit' => 120,
                'bag_20x30_unit' => 120,
                'bag_35x45_unit' => 120,
                'bubble_wrap_5x10_unit' => 120,
                'bubble_wrap_10x15_unit' => 120,
                'bubble_wrap_20x30_unit' => 120,
                'production_time' => '6 dias',
            ],
            [
                'quantity_from' => 5000,
                'quantity_to' => 9999,
                'cost_without_assembly' => 130,
                'cost_with_assembly' => 130,
                'palletizing_without_pallet' => 130,
                'palletizing_with_pallet' => 130,
                'cost_with_labeling' => 130,
                'cost_without_labeling' => 130,
                'dome_sticking_unit' => 130,
                'additional_assembly' => 130,
                'quality_control' => 130,
                'shavings_50g_unit' => 130,
                'shavings_100g_unit' => 130,
                'shavings_200g_unit' => 130,
                'bag_10x15_unit' => 130,
                'bag_20x30_unit' => 130,
                'bag_35x45_unit' => 130,
                'bubble_wrap_5x10_unit' => 130,
                'bubble_wrap_10x15_unit' => 130,
                'bubble_wrap_20x30_unit' => 130,
                'production_time' => '7 dias',
            ],
            [
                'quantity_from' => 10000,
                'quantity_to' => 14999,
                'cost_without_assembly' => 140,
                'cost_with_assembly' => 140,
                'palletizing_without_pallet' => 140,
                'palletizing_with_pallet' => 140,
                'cost_with_labeling' => 140,
                'cost_without_labeling' => 140,
                'dome_sticking_unit' => 140,
                'additional_assembly' => 140,
                'quality_control' => 140,
                'shavings_50g_unit' => 140,
                'shavings_100g_unit' => 140,
                'shavings_200g_unit' => 140,
                'bag_10x15_unit' => 140,
                'bag_20x30_unit' => 140,
                'bag_35x45_unit' => 140,
                'bubble_wrap_5x10_unit' => 140,
                'bubble_wrap_10x15_unit' => 140,
                'bubble_wrap_20x30_unit' => 140,
                'production_time' => '10 dias',
            ],
            [
                'quantity_from' => 15000,
                'quantity_to' => 17999,
                'cost_without_assembly' => 150,
                'cost_with_assembly' => 150,
                'palletizing_without_pallet' => 150,
                'palletizing_with_pallet' => 150,
                'cost_with_labeling' => 150,
                'cost_without_labeling' => 150,
                'dome_sticking_unit' => 150,
                'additional_assembly' => 150,
                'quality_control' => 150,
                'shavings_50g_unit' => 150,
                'shavings_100g_unit' => 150,
                'shavings_200g_unit' => 150,
                'bag_10x15_unit' => 150,
                'bag_20x30_unit' => 150,
                'bag_35x45_unit' => 150,
                'bubble_wrap_5x10_unit' => 150,
                'bubble_wrap_10x15_unit' => 150,
                'bubble_wrap_20x30_unit' => 150,
                'production_time' => '14 dias',
            ],
            [
                'quantity_from' => 18000,
                'quantity_to' => null, // "o más"
                'cost_without_assembly' => 160,
                'cost_with_assembly' => 160,
                'palletizing_without_pallet' => 160,
                'palletizing_with_pallet' => 160,
                'cost_with_labeling' => 160,
                'cost_without_labeling' => 160,
                'dome_sticking_unit' => 160,
                'additional_assembly' => 160,
                'quality_control' => 160,
                'shavings_50g_unit' => 160,
                'shavings_100g_unit' => 160,
                'shavings_200g_unit' => 160,
                'bag_10x15_unit' => 160,
                'bag_20x30_unit' => 160,
                'bag_35x45_unit' => 160,
                'bubble_wrap_5x10_unit' => 160,
                'bubble_wrap_10x15_unit' => 160,
                'bubble_wrap_20x30_unit' => 160,
                'production_time' => '17 dias aprox.',
            ],
        ];


        foreach ($scales as $scale) {
            PickingCostScale::create(array_merge($scale, ['is_active' => true]));
        }

        $this->command->info('✓ ' . count($scales) . ' escalas de costos creadas correctamente');
    }
}
