<?php

namespace Database\Seeders;

use App\Models\PickingCostScale;
use Illuminate\Database\Seeder;

class PickingCostScaleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $scales = [
            [
                'quantity_from' => 1,
                'quantity_to' => 49,
                'cost_without_assembly' => 10,
                'cost_with_assembly' => 11,
                'palletizing_without_pallet' => 10,
                'palletizing_with_pallet' => 11,
                'cost_with_labeling' => 11,
                'cost_without_labeling' => 10,
                'dome_sticking_unit' => 15,
                'additional_assembly' => 16,
                'quality_control' => 18,
                'shavings_50g_unit' => 10,
                'shavings_100g_unit' => 12,
                'shavings_200g_unit' => 14,
                'bag_10x15_unit' => 10,
                'bag_20x30_unit' => 12,
                'bag_35x45_unit' => 14,
                'bubble_wrap_5x10_unit' => 10,
                'bubble_wrap_10x15_unit' => 12,
                'bubble_wrap_20x30_unit' => 14,
                'production_time' => '24 hs',
            ],
            [
                'quantity_from' => 50,
                'quantity_to' => 84,
                'cost_without_assembly' => 20,
                'cost_with_assembly' => 21,
                'palletizing_without_pallet' => 20,
                'palletizing_with_pallet' => 21,
                'cost_with_labeling' => 21,
                'cost_without_labeling' => 20,
                'dome_sticking_unit' => 25,
                'additional_assembly' => 26,
                'quality_control' => 28,
                'shavings_50g_unit' => 20,
                'shavings_100g_unit' => 22,
                'shavings_200g_unit' => 24,
                'bag_10x15_unit' => 20,
                'bag_20x30_unit' => 22,
                'bag_35x45_unit' => 24,
                'bubble_wrap_5x10_unit' => 20,
                'bubble_wrap_10x15_unit' => 22,
                'bubble_wrap_20x30_unit' => 24,
                'production_time' => '24 hs',
            ],
            [
                'quantity_from' => 85,
                'quantity_to' => 99,
                'cost_without_assembly' => 30,
                'cost_with_assembly' => 31,
                'palletizing_without_pallet' => 30,
                'palletizing_with_pallet' => 31,
                'cost_with_labeling' => 31,
                'cost_without_labeling' => 30,
                'dome_sticking_unit' => 35,
                'additional_assembly' => 36,
                'quality_control' => 38,
                'shavings_50g_unit' => 30,
                'shavings_100g_unit' => 32,
                'shavings_200g_unit' => 34,
                'bag_10x15_unit' => 30,
                'bag_20x30_unit' => 32,
                'bag_35x45_unit' => 34,
                'bubble_wrap_5x10_unit' => 30,
                'bubble_wrap_10x15_unit' => 32,
                'bubble_wrap_20x30_unit' => 34,
                'production_time' => '48 hs',
            ],
            [
                'quantity_from' => 100,
                'quantity_to' => 149,
                'cost_without_assembly' => 40,
                'cost_with_assembly' => 41,
                'palletizing_without_pallet' => 40,
                'palletizing_with_pallet' => 41,
                'cost_with_labeling' => 41,
                'cost_without_labeling' => 40,
                'dome_sticking_unit' => 45,
                'additional_assembly' => 46,
                'quality_control' => 48,
                'shavings_50g_unit' => 40,
                'shavings_100g_unit' => 42,
                'shavings_200g_unit' => 44,
                'bag_10x15_unit' => 40,
                'bag_20x30_unit' => 42,
                'bag_35x45_unit' => 44,
                'bubble_wrap_5x10_unit' => 40,
                'bubble_wrap_10x15_unit' => 42,
                'bubble_wrap_20x30_unit' => 44,
                'production_time' => '48 hs',
            ],
            [
                'quantity_from' => 150,
                'quantity_to' => 249,
                'cost_without_assembly' => 50,
                'cost_with_assembly' => 51,
                'palletizing_without_pallet' => 50,
                'palletizing_with_pallet' => 51,
                'cost_with_labeling' => 51,
                'cost_without_labeling' => 50,
                'dome_sticking_unit' => 55,
                'additional_assembly' => 56,
                'quality_control' => 58,
                'shavings_50g_unit' => 50,
                'shavings_100g_unit' => 52,
                'shavings_200g_unit' => 54,
                'bag_10x15_unit' => 50,
                'bag_20x30_unit' => 52,
                'bag_35x45_unit' => 54,
                'bubble_wrap_5x10_unit' => 50,
                'bubble_wrap_10x15_unit' => 52,
                'bubble_wrap_20x30_unit' => 54,
                'production_time' => '72 hs',
            ],
            [
                'quantity_from' => 250,
                'quantity_to' => 299,
                'cost_without_assembly' => 60,
                'cost_with_assembly' => 61,
                'palletizing_without_pallet' => 60,
                'palletizing_with_pallet' => 61,
                'cost_with_labeling' => 61,
                'cost_without_labeling' => 60,
                'dome_sticking_unit' => 65,
                'additional_assembly' => 66,
                'quality_control' => 68,
                'shavings_50g_unit' => 60,
                'shavings_100g_unit' => 62,
                'shavings_200g_unit' => 64,
                'bag_10x15_unit' => 60,
                'bag_20x30_unit' => 62,
                'bag_35x45_unit' => 64,
                'bubble_wrap_5x10_unit' => 60,
                'bubble_wrap_10x15_unit' => 62,
                'bubble_wrap_20x30_unit' => 64,
                'production_time' => '72 hs',
            ],
            [
                'quantity_from' => 300,
                'quantity_to' => 399,
                'cost_without_assembly' => 70,
                'cost_with_assembly' => 71,
                'palletizing_without_pallet' => 70,
                'palletizing_with_pallet' => 71,
                'cost_with_labeling' => 71,
                'cost_without_labeling' => 70,
                'dome_sticking_unit' => 75,
                'additional_assembly' => 76,
                'quality_control' => 78,
                'shavings_50g_unit' => 70,
                'shavings_100g_unit' => 72,
                'shavings_200g_unit' => 74,
                'bag_10x15_unit' => 70,
                'bag_20x30_unit' => 72,
                'bag_35x45_unit' => 74,
                'bubble_wrap_5x10_unit' => 70,
                'bubble_wrap_10x15_unit' => 72,
                'bubble_wrap_20x30_unit' => 74,
                'production_time' => '3 dias',
            ],
            [
                'quantity_from' => 400,
                'quantity_to' => 499,
                'cost_without_assembly' => 80,
                'cost_with_assembly' => 81,
                'palletizing_without_pallet' => 80,
                'palletizing_with_pallet' => 81,
                'cost_with_labeling' => 81,
                'cost_without_labeling' => 80,
                'dome_sticking_unit' => 85,
                'additional_assembly' => 86,
                'quality_control' => 88,
                'shavings_50g_unit' => 80,
                'shavings_100g_unit' => 82,
                'shavings_200g_unit' => 84,
                'bag_10x15_unit' => 80,
                'bag_20x30_unit' => 82,
                'bag_35x45_unit' => 84,
                'bubble_wrap_5x10_unit' => 80,
                'bubble_wrap_10x15_unit' => 82,
                'bubble_wrap_20x30_unit' => 84,
                'production_time' => '4 dias',
            ],
            [
                'quantity_from' => 500,
                'quantity_to' => 799,
                'cost_without_assembly' => 90,
                'cost_with_assembly' => 91,
                'palletizing_without_pallet' => 90,
                'palletizing_with_pallet' => 91,
                'cost_with_labeling' => 91,
                'cost_without_labeling' => 90,
                'dome_sticking_unit' => 95,
                'additional_assembly' => 96,
                'quality_control' => 98,
                'shavings_50g_unit' => 90,
                'shavings_100g_unit' => 92,
                'shavings_200g_unit' => 94,
                'bag_10x15_unit' => 90,
                'bag_20x30_unit' => 92,
                'bag_35x45_unit' => 94,
                'bubble_wrap_5x10_unit' => 90,
                'bubble_wrap_10x15_unit' => 92,
                'bubble_wrap_20x30_unit' => 94,
                'production_time' => '4 dias',
            ],
            [
                'quantity_from' => 800,
                'quantity_to' => 999,
                'cost_without_assembly' => 100,
                'cost_with_assembly' => 101,
                'palletizing_without_pallet' => 100,
                'palletizing_with_pallet' => 101,
                'cost_with_labeling' => 101,
                'cost_without_labeling' => 100,
                'dome_sticking_unit' => 105,
                'additional_assembly' => 106,
                'quality_control' => 108,
                'shavings_50g_unit' => 100,
                'shavings_100g_unit' => 102,
                'shavings_200g_unit' => 104,
                'bag_10x15_unit' => 100,
                'bag_20x30_unit' => 102,
                'bag_35x45_unit' => 104,
                'bubble_wrap_5x10_unit' => 100,
                'bubble_wrap_10x15_unit' => 102,
                'bubble_wrap_20x30_unit' => 104,
                'production_time' => '4 dias',
            ],
            [
                'quantity_from' => 1000,
                'quantity_to' => 1999,
                'cost_without_assembly' => 110,
                'cost_with_assembly' => 111,
                'palletizing_without_pallet' => 110,
                'palletizing_with_pallet' => 111,
                'cost_with_labeling' => 111,
                'cost_without_labeling' => 110,
                'dome_sticking_unit' => 115,
                'additional_assembly' => 116,
                'quality_control' => 118,
                'shavings_50g_unit' => 110,
                'shavings_100g_unit' => 112,
                'shavings_200g_unit' => 114,
                'bag_10x15_unit' => 110,
                'bag_20x30_unit' => 112,
                'bag_35x45_unit' => 114,
                'bubble_wrap_5x10_unit' => 110,
                'bubble_wrap_10x15_unit' => 112,
                'bubble_wrap_20x30_unit' => 114,
                'production_time' => '5 dias',
            ],
            [
                'quantity_from' => 2000,
                'quantity_to' => 4999,
                'cost_without_assembly' => 120,
                'cost_with_assembly' => 121,
                'palletizing_without_pallet' => 120,
                'palletizing_with_pallet' => 121,
                'cost_with_labeling' => 121,
                'cost_without_labeling' => 120,
                'dome_sticking_unit' => 125,
                'additional_assembly' => 126,
                'quality_control' => 128,
                'shavings_50g_unit' => 120,
                'shavings_100g_unit' => 122,
                'shavings_200g_unit' => 124,
                'bag_10x15_unit' => 120,
                'bag_20x30_unit' => 122,
                'bag_35x45_unit' => 124,
                'bubble_wrap_5x10_unit' => 120,
                'bubble_wrap_10x15_unit' => 122,
                'bubble_wrap_20x30_unit' => 124,
                'production_time' => '6 dias',
            ],
            [
                'quantity_from' => 5000,
                'quantity_to' => 9999,
                'cost_without_assembly' => 130,
                'cost_with_assembly' => 131,
                'palletizing_without_pallet' => 130,
                'palletizing_with_pallet' => 131,
                'cost_with_labeling' => 131,
                'cost_without_labeling' => 130,
                'dome_sticking_unit' => 135,
                'additional_assembly' => 136,
                'quality_control' => 138,
                'shavings_50g_unit' => 130,
                'shavings_100g_unit' => 132,
                'shavings_200g_unit' => 134,
                'bag_10x15_unit' => 130,
                'bag_20x30_unit' => 132,
                'bag_35x45_unit' => 134,
                'bubble_wrap_5x10_unit' => 130,
                'bubble_wrap_10x15_unit' => 132,
                'bubble_wrap_20x30_unit' => 134,
                'production_time' => '7 dias',
            ],
            [
                'quantity_from' => 10000,
                'quantity_to' => 14999,
                'cost_without_assembly' => 140,
                'cost_with_assembly' => 141,
                'palletizing_without_pallet' => 140,
                'palletizing_with_pallet' => 141,
                'cost_with_labeling' => 141,
                'cost_without_labeling' => 140,
                'dome_sticking_unit' => 145,
                'additional_assembly' => 146,
                'quality_control' => 148,
                'shavings_50g_unit' => 140,
                'shavings_100g_unit' => 142,
                'shavings_200g_unit' => 144,
                'bag_10x15_unit' => 140,
                'bag_20x30_unit' => 142,
                'bag_35x45_unit' => 144,
                'bubble_wrap_5x10_unit' => 140,
                'bubble_wrap_10x15_unit' => 142,
                'bubble_wrap_20x30_unit' => 144,
                'production_time' => '10 dias',
            ],
            [
                'quantity_from' => 15000,
                'quantity_to' => 17999,
                'cost_without_assembly' => 150,
                'cost_with_assembly' => 151,
                'palletizing_without_pallet' => 150,
                'palletizing_with_pallet' => 151,
                'cost_with_labeling' => 151,
                'cost_without_labeling' => 150,
                'dome_sticking_unit' => 155,
                'additional_assembly' => 156,
                'quality_control' => 158,
                'shavings_50g_unit' => 150,
                'shavings_100g_unit' => 152,
                'shavings_200g_unit' => 154,
                'bag_10x15_unit' => 150,
                'bag_20x30_unit' => 152,
                'bag_35x45_unit' => 154,
                'bubble_wrap_5x10_unit' => 150,
                'bubble_wrap_10x15_unit' => 152,
                'bubble_wrap_20x30_unit' => 154,
                'production_time' => '14 dias',
            ],
            [
                'quantity_from' => 18000,
                'quantity_to' => null, // "o más"
                'cost_without_assembly' => 160,
                'cost_with_assembly' => 161,
                'palletizing_without_pallet' => 160,
                'palletizing_with_pallet' => 161,
                'cost_with_labeling' => 161,
                'cost_without_labeling' => 160,
                'dome_sticking_unit' => 165,
                'additional_assembly' => 166,
                'quality_control' => 168,
                'shavings_50g_unit' => 160,
                'shavings_100g_unit' => 162,
                'shavings_200g_unit' => 164,
                'bag_10x15_unit' => 160,
                'bag_20x30_unit' => 162,
                'bag_35x45_unit' => 164,
                'bubble_wrap_5x10_unit' => 160,
                'bubble_wrap_10x15_unit' => 162,
                'bubble_wrap_20x30_unit' => 164,
                'production_time' => '17 dias aprox.',
            ],
        ];

        foreach ($scales as $scale) {
            PickingCostScale::create(array_merge($scale, ['is_active' => true]));
        }

        $this->command->info('✓ ' . count($scales) . ' escalas de costos creadas correctamente');
    }
}
